version: '3.8'

services:
  zalo-aqi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: zalo-aqi
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
